#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_split_3x6_3_ex2(KC_ESC, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_LEFT, KC_RGHT, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC, KC_LSFT, KC_A, KC_S, KC_D, KC_F, KC_G, KC_UP, KC_DOWN, KC_H, KC_J, KC_K, KC_L, KC_QUOT, KC_ASTR, MO(1), KC_Z, KC_X, KC_C, KC_V, KC_B, KC_N, KC_M, KC_LBRC, KC_RBRC, KC_COMM, KC_DOT, KC_LCTL, KC_LGUI, KC_SPC, KC_ENT, KC_RALT, MO(1)),
    [1] = LAYOUT_split_3x6_3_ex2(KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_LEFT, KC_RGHT, KC_6, KC_7, KC_8, KC_9, KC_0, KC_BSPC, KC_LSFT, KC_EXLM, KC_AT, KC_QUES, KC_DLR, KC_PERC, KC_UP, KC_DOWN, KC_EQL, KC_MINS, KC_UNDS, KC_SCLN, KC_GRV, KC_HASH, KC_TRNS, KC_PIPE, KC_PLUS, KC_AMPR, KC_CIRC, KC_NO, KC_LT, KC_GT, KC_LPRN, KC_RPRN, KC_SLSH, KC_BSLS, KC_LCTL, KC_LGUI, KC_TAB, KC_ENT, KC_RALT, KC_TRNS)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

